apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
data:
  config.yaml: |
    kafka:
      clusters:
        - name: local
          bootstrapServers: "kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/kafkaui
      volumes:
        - name: config
          configMap:
            name: kafka-ui-config

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
